// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 001_users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, hashed_password, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    NOW()
)
RETURNING id, username, email, created_at, updated_at, hashed_password
`

type CreateUserParams struct {
	Username       string         `json:"username"`
	Email          string         `json:"email"`
	HashedPassword sql.NullString `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
	)
	return i, err
}

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, created_at, updated_at, hashed_password FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT users.id, users.username, email, users.created_at, users.updated_at, hashed_password, strava_user.id, user_id, strava_id, strava_user.created_at, strava_user.updated_at, strava_user.username, firstname, lastname, city, state, country, sex, premuim, weight FROM users
join STRAVA_USER on users.id = STRAVA_USER.user_id
WHERE users.id = $1
`

type GetUserByIDRow struct {
	ID             uuid.UUID       `json:"id"`
	Username       string          `json:"username"`
	Email          string          `json:"email"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	HashedPassword sql.NullString  `json:"hashed_password"`
	ID_2           uuid.UUID       `json:"id_2"`
	UserID         uuid.UUID       `json:"user_id"`
	StravaID       int64           `json:"strava_id"`
	CreatedAt_2    time.Time       `json:"created_at_2"`
	UpdatedAt_2    time.Time       `json:"updated_at_2"`
	Username_2     string          `json:"username_2"`
	Firstname      sql.NullString  `json:"firstname"`
	Lastname       sql.NullString  `json:"lastname"`
	City           sql.NullString  `json:"city"`
	State          sql.NullString  `json:"state"`
	Country        sql.NullString  `json:"country"`
	Sex            sql.NullString  `json:"sex"`
	Premuim        sql.NullBool    `json:"premuim"`
	Weight         sql.NullFloat64 `json:"weight"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
		&i.ID_2,
		&i.UserID,
		&i.StravaID,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.Username_2,
		&i.Firstname,
		&i.Lastname,
		&i.City,
		&i.State,
		&i.Country,
		&i.Sex,
		&i.Premuim,
		&i.Weight,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
Set hashed_password = $2,
    updated_at = NOW()
Where id=$1
`

type UpdatePasswordParams struct {
	ID             uuid.UUID      `json:"id"`
	HashedPassword sql.NullString `json:"hashed_password"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.ID, arg.HashedPassword)
	return err
}
