// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 002_strava_users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStravaUser = `-- name: CreateStravaUser :one
INSERT INTO strava_user (id, user_id, strava_id, created_at,updated_at, username, firstname, lastname, city, state, country, sex,
    premuim, weight)
VALUES (
    gen_random_uuid(),
    $1,$2,NOW(),NOW(),$3,$4,$5,$6,$7,$8,$9,$10,$11
)
RETURNING  id, user_id, strava_id, created_at, updated_at, username, firstname, lastname, city, state, country, sex, premuim, weight
`

type CreateStravaUserParams struct {
	UserID    uuid.UUID       `json:"user_id"`
	StravaID  int64           `json:"strava_id"`
	Username  string          `json:"username"`
	Firstname sql.NullString  `json:"firstname"`
	Lastname  sql.NullString  `json:"lastname"`
	City      sql.NullString  `json:"city"`
	State     sql.NullString  `json:"state"`
	Country   sql.NullString  `json:"country"`
	Sex       sql.NullString  `json:"sex"`
	Premuim   sql.NullBool    `json:"premuim"`
	Weight    sql.NullFloat64 `json:"weight"`
}

func (q *Queries) CreateStravaUser(ctx context.Context, arg CreateStravaUserParams) (StravaUser, error) {
	row := q.db.QueryRowContext(ctx, createStravaUser,
		arg.UserID,
		arg.StravaID,
		arg.Username,
		arg.Firstname,
		arg.Lastname,
		arg.City,
		arg.State,
		arg.Country,
		arg.Sex,
		arg.Premuim,
		arg.Weight,
	)
	var i StravaUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StravaID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.City,
		&i.State,
		&i.Country,
		&i.Sex,
		&i.Premuim,
		&i.Weight,
	)
	return i, err
}

const getStravaUserByUserID = `-- name: GetStravaUserByUserID :one
SELECT id, user_id, strava_id, created_at, updated_at, username, firstname, lastname, city, state, country, sex, premuim, weight FROM strava_user
WHERE user_id = $1
`

func (q *Queries) GetStravaUserByUserID(ctx context.Context, userID uuid.UUID) (StravaUser, error) {
	row := q.db.QueryRowContext(ctx, getStravaUserByUserID, userID)
	var i StravaUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StravaID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.City,
		&i.State,
		&i.Country,
		&i.Sex,
		&i.Premuim,
		&i.Weight,
	)
	return i, err
}
