// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 003_strava_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createStravaAccessToken = `-- name: CreateStravaAccessToken :one
INSERT INTO strava_tokens (id, strava_user_id, access_token, token_type, expires_at, refresh_token, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,$2,$3,$4,$5,NOW(),NOW()
)
RETURNING  id, strava_user_id, access_token, token_type, expires_at, refresh_token, created_at, updated_at
`

type CreateStravaAccessTokenParams struct {
	StravaUserID uuid.UUID `json:"strava_user_id"`
	AccessToken  string    `json:"access_token"`
	TokenType    string    `json:"token_type"`
	ExpiresAt    time.Time `json:"expires_at"`
	RefreshToken string    `json:"refresh_token"`
}

func (q *Queries) CreateStravaAccessToken(ctx context.Context, arg CreateStravaAccessTokenParams) (StravaToken, error) {
	row := q.db.QueryRowContext(ctx, createStravaAccessToken,
		arg.StravaUserID,
		arg.AccessToken,
		arg.TokenType,
		arg.ExpiresAt,
		arg.RefreshToken,
	)
	var i StravaToken
	err := row.Scan(
		&i.ID,
		&i.StravaUserID,
		&i.AccessToken,
		&i.TokenType,
		&i.ExpiresAt,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllStravaAccessTokens = `-- name: DeleteAllStravaAccessTokens :exec
DELETE FROM strava_tokens
`

func (q *Queries) DeleteAllStravaAccessTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllStravaAccessTokens)
	return err
}

const getStravaAccessTokenByUserID = `-- name: GetStravaAccessTokenByUserID :one
SELECT id, strava_user_id, access_token, token_type, expires_at, refresh_token, created_at, updated_at FROM strava_tokens
WHERE strava_user_id = $1
`

func (q *Queries) GetStravaAccessTokenByUserID(ctx context.Context, stravaUserID uuid.UUID) (StravaToken, error) {
	row := q.db.QueryRowContext(ctx, getStravaAccessTokenByUserID, stravaUserID)
	var i StravaToken
	err := row.Scan(
		&i.ID,
		&i.StravaUserID,
		&i.AccessToken,
		&i.TokenType,
		&i.ExpiresAt,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStravaAccessTokensByApplicationUserID = `-- name: GetStravaAccessTokensByApplicationUserID :one
SELECT st.id, strava_user_id, access_token, token_type, expires_at, refresh_token, st.created_at, st.updated_at, su.id, user_id, strava_id, su.created_at, su.updated_at, username, firstname, lastname, city, state, country, sex, premuim, weight FROM strava_tokens st
JOIN strava_user su ON su.id = st.strava_user_id
WHERE su.user_id = $1
`

type GetStravaAccessTokensByApplicationUserIDRow struct {
	ID           uuid.UUID      `json:"id"`
	StravaUserID uuid.UUID      `json:"strava_user_id"`
	AccessToken  string         `json:"access_token"`
	TokenType    string         `json:"token_type"`
	ExpiresAt    time.Time      `json:"expires_at"`
	RefreshToken string         `json:"refresh_token"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ID_2         uuid.UUID      `json:"id_2"`
	UserID       uuid.UUID      `json:"user_id"`
	StravaID     int64          `json:"strava_id"`
	CreatedAt_2  time.Time      `json:"created_at_2"`
	UpdatedAt_2  time.Time      `json:"updated_at_2"`
	Username     string         `json:"username"`
	Firstname    sql.NullString `json:"firstname"`
	Lastname     sql.NullString `json:"lastname"`
	City         sql.NullString `json:"city"`
	State        sql.NullString `json:"state"`
	Country      sql.NullString `json:"country"`
	Sex          sql.NullString `json:"sex"`
	Premuim      sql.NullBool   `json:"premuim"`
	Weight       sql.NullInt32  `json:"weight"`
}

func (q *Queries) GetStravaAccessTokensByApplicationUserID(ctx context.Context, userID uuid.UUID) (GetStravaAccessTokensByApplicationUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getStravaAccessTokensByApplicationUserID, userID)
	var i GetStravaAccessTokensByApplicationUserIDRow
	err := row.Scan(
		&i.ID,
		&i.StravaUserID,
		&i.AccessToken,
		&i.TokenType,
		&i.ExpiresAt,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ID_2,
		&i.UserID,
		&i.StravaID,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.City,
		&i.State,
		&i.Country,
		&i.Sex,
		&i.Premuim,
		&i.Weight,
	)
	return i, err
}

const updateStravaAccessToken = `-- name: UpdateStravaAccessToken :exec
UPDATE strava_tokens
SET access_token = $2,
    token_type = $3,
    expires_at = $4,
    refresh_token = $5,
    updated_at = NOW()
Where strava_user_id=$1
`

type UpdateStravaAccessTokenParams struct {
	StravaUserID uuid.UUID `json:"strava_user_id"`
	AccessToken  string    `json:"access_token"`
	TokenType    string    `json:"token_type"`
	ExpiresAt    time.Time `json:"expires_at"`
	RefreshToken string    `json:"refresh_token"`
}

func (q *Queries) UpdateStravaAccessToken(ctx context.Context, arg UpdateStravaAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateStravaAccessToken,
		arg.StravaUserID,
		arg.AccessToken,
		arg.TokenType,
		arg.ExpiresAt,
		arg.RefreshToken,
	)
	return err
}
