// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 005_strava_activities.sql

package database

import (
	"context"
	"database/sql"
)

const createStravaActivity = `-- name: CreateStravaActivity :exec
INSERT INTO strava_activities (
    id,
    external_id,
    upload_id,
    athlete_id,
    name,
    description,
    distance,
    moving_time,
    elapsed_time,
    total_elevation_gain,
    elev_high,
    elev_low,
    type,
    sport_type,
    start_date,
    start_date_local,
    timezone,
    average_speed,
    max_speed,
    average_cadence,
    average_heartrate,
    max_heartrate,
    calories,
    workout_type,
    kudos_count,
    comment_count,
    achievement_count,
    photo_count,
    trainer,
    commute,
    manual,
    private,
    visibility,
    flagged,
    gear_id,
    map_summary
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36
)
`

type CreateStravaActivityParams struct {
	ID                 int64           `json:"id"`
	ExternalID         sql.NullString  `json:"external_id"`
	UploadID           sql.NullInt64   `json:"upload_id"`
	AthleteID          sql.NullInt64   `json:"athlete_id"`
	Name               sql.NullString  `json:"name"`
	Description        sql.NullString  `json:"description"`
	Distance           sql.NullFloat64 `json:"distance"`
	MovingTime         sql.NullInt32   `json:"moving_time"`
	ElapsedTime        sql.NullInt32   `json:"elapsed_time"`
	TotalElevationGain sql.NullFloat64 `json:"total_elevation_gain"`
	ElevHigh           sql.NullFloat64 `json:"elev_high"`
	ElevLow            sql.NullFloat64 `json:"elev_low"`
	Type               sql.NullString  `json:"type"`
	SportType          sql.NullString  `json:"sport_type"`
	StartDate          sql.NullTime    `json:"start_date"`
	StartDateLocal     sql.NullTime    `json:"start_date_local"`
	Timezone           sql.NullString  `json:"timezone"`
	AverageSpeed       sql.NullFloat64 `json:"average_speed"`
	MaxSpeed           sql.NullFloat64 `json:"max_speed"`
	AverageCadence     sql.NullFloat64 `json:"average_cadence"`
	AverageHeartrate   sql.NullFloat64 `json:"average_heartrate"`
	MaxHeartrate       sql.NullFloat64 `json:"max_heartrate"`
	Calories           sql.NullFloat64 `json:"calories"`
	WorkoutType        sql.NullInt32   `json:"workout_type"`
	KudosCount         sql.NullInt32   `json:"kudos_count"`
	CommentCount       sql.NullInt32   `json:"comment_count"`
	AchievementCount   sql.NullInt32   `json:"achievement_count"`
	PhotoCount         sql.NullInt32   `json:"photo_count"`
	Trainer            sql.NullBool    `json:"trainer"`
	Commute            sql.NullBool    `json:"commute"`
	Manual             sql.NullBool    `json:"manual"`
	Private            sql.NullBool    `json:"private"`
	Visibility         sql.NullString  `json:"visibility"`
	Flagged            sql.NullBool    `json:"flagged"`
	GearID             sql.NullString  `json:"gear_id"`
	MapSummary         sql.NullString  `json:"map_summary"`
}

func (q *Queries) CreateStravaActivity(ctx context.Context, arg CreateStravaActivityParams) error {
	_, err := q.db.ExecContext(ctx, createStravaActivity,
		arg.ID,
		arg.ExternalID,
		arg.UploadID,
		arg.AthleteID,
		arg.Name,
		arg.Description,
		arg.Distance,
		arg.MovingTime,
		arg.ElapsedTime,
		arg.TotalElevationGain,
		arg.ElevHigh,
		arg.ElevLow,
		arg.Type,
		arg.SportType,
		arg.StartDate,
		arg.StartDateLocal,
		arg.Timezone,
		arg.AverageSpeed,
		arg.MaxSpeed,
		arg.AverageCadence,
		arg.AverageHeartrate,
		arg.MaxHeartrate,
		arg.Calories,
		arg.WorkoutType,
		arg.KudosCount,
		arg.CommentCount,
		arg.AchievementCount,
		arg.PhotoCount,
		arg.Trainer,
		arg.Commute,
		arg.Manual,
		arg.Private,
		arg.Visibility,
		arg.Flagged,
		arg.GearID,
		arg.MapSummary,
	)
	return err
}

const getStravaActivitiesByAthleteID = `-- name: GetStravaActivitiesByAthleteID :many
SELECT id, external_id, upload_id, athlete_id, name, description, distance, moving_time, elapsed_time, total_elevation_gain, elev_high, elev_low, type, sport_type, start_date, start_date_local, timezone, average_speed, max_speed, average_cadence, average_heartrate, max_heartrate, calories, workout_type, kudos_count, comment_count, achievement_count, photo_count, trainer, commute, manual, private, visibility, flagged, gear_id, map_summary, created_at, updated_at FROM strava_activities
WHERE athlete_id = $1
ORDER BY start_date DESC
`

func (q *Queries) GetStravaActivitiesByAthleteID(ctx context.Context, athleteID sql.NullInt64) ([]StravaActivity, error) {
	rows, err := q.db.QueryContext(ctx, getStravaActivitiesByAthleteID, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StravaActivity
	for rows.Next() {
		var i StravaActivity
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.UploadID,
			&i.AthleteID,
			&i.Name,
			&i.Description,
			&i.Distance,
			&i.MovingTime,
			&i.ElapsedTime,
			&i.TotalElevationGain,
			&i.ElevHigh,
			&i.ElevLow,
			&i.Type,
			&i.SportType,
			&i.StartDate,
			&i.StartDateLocal,
			&i.Timezone,
			&i.AverageSpeed,
			&i.MaxSpeed,
			&i.AverageCadence,
			&i.AverageHeartrate,
			&i.MaxHeartrate,
			&i.Calories,
			&i.WorkoutType,
			&i.KudosCount,
			&i.CommentCount,
			&i.AchievementCount,
			&i.PhotoCount,
			&i.Trainer,
			&i.Commute,
			&i.Manual,
			&i.Private,
			&i.Visibility,
			&i.Flagged,
			&i.GearID,
			&i.MapSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
