// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 006_strava_segments.sql

package database

import (
	"context"
	"database/sql"
)

const createStravaSegment = `-- name: CreateStravaSegment :exec
INSERT INTO strava_segments (
    id,
    activity_id,
    elapsed_time,
    start_date,
    start_date_local,
    distance,
    moving_time,
    start_index,
    end_index,
    average_cadence,
    average_watts,
    average_heartrate,
    max_heartrate   
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
`

type CreateStravaSegmentParams struct {
	ID               int64           `json:"id"`
	ActivityID       sql.NullInt64   `json:"activity_id"`
	ElapsedTime      sql.NullInt32   `json:"elapsed_time"`
	StartDate        sql.NullString  `json:"start_date"`
	StartDateLocal   sql.NullString  `json:"start_date_local"`
	Distance         sql.NullFloat64 `json:"distance"`
	MovingTime       sql.NullInt32   `json:"moving_time"`
	StartIndex       sql.NullInt32   `json:"start_index"`
	EndIndex         sql.NullInt32   `json:"end_index"`
	AverageCadence   sql.NullFloat64 `json:"average_cadence"`
	AverageWatts     sql.NullFloat64 `json:"average_watts"`
	AverageHeartrate sql.NullFloat64 `json:"average_heartrate"`
	MaxHeartrate     sql.NullFloat64 `json:"max_heartrate"`
}

func (q *Queries) CreateStravaSegment(ctx context.Context, arg CreateStravaSegmentParams) error {
	_, err := q.db.ExecContext(ctx, createStravaSegment,
		arg.ID,
		arg.ActivityID,
		arg.ElapsedTime,
		arg.StartDate,
		arg.StartDateLocal,
		arg.Distance,
		arg.MovingTime,
		arg.StartIndex,
		arg.EndIndex,
		arg.AverageCadence,
		arg.AverageWatts,
		arg.AverageHeartrate,
		arg.MaxHeartrate,
	)
	return err
}
