// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: 007_strava_laps.sql

package database

import (
	"context"
	"database/sql"
)

const createStravaLap = `-- name: CreateStravaLap :exec
INSERT INTO strava_laps (
    id,
    activity_id,
    athlete_id,
    average_cadence,
    average_speed,
    average_heartrate,
    max_heartrate,
    distance,
    elapsed_time,
    start_index,
    end_index,
    lap_index,
    max_speed,
    moving_time,
    name,
    pace_zone,
    split,
    start_date,
    start_date_local,
    total_elevation_gain
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
`

type CreateStravaLapParams struct {
	ID                 int64           `json:"id"`
	ActivityID         sql.NullInt64   `json:"activity_id"`
	AthleteID          sql.NullInt64   `json:"athlete_id"`
	AverageCadence     sql.NullFloat64 `json:"average_cadence"`
	AverageSpeed       sql.NullFloat64 `json:"average_speed"`
	AverageHeartrate   sql.NullFloat64 `json:"average_heartrate"`
	MaxHeartrate       sql.NullFloat64 `json:"max_heartrate"`
	Distance           sql.NullFloat64 `json:"distance"`
	ElapsedTime        sql.NullInt32   `json:"elapsed_time"`
	StartIndex         sql.NullInt32   `json:"start_index"`
	EndIndex           sql.NullInt32   `json:"end_index"`
	LapIndex           sql.NullInt32   `json:"lap_index"`
	MaxSpeed           sql.NullFloat64 `json:"max_speed"`
	MovingTime         sql.NullInt32   `json:"moving_time"`
	Name               sql.NullString  `json:"name"`
	PaceZone           sql.NullInt32   `json:"pace_zone"`
	Split              sql.NullInt32   `json:"split"`
	StartDate          sql.NullString  `json:"start_date"`
	StartDateLocal     sql.NullString  `json:"start_date_local"`
	TotalElevationGain sql.NullFloat64 `json:"total_elevation_gain"`
}

func (q *Queries) CreateStravaLap(ctx context.Context, arg CreateStravaLapParams) error {
	_, err := q.db.ExecContext(ctx, createStravaLap,
		arg.ID,
		arg.ActivityID,
		arg.AthleteID,
		arg.AverageCadence,
		arg.AverageSpeed,
		arg.AverageHeartrate,
		arg.MaxHeartrate,
		arg.Distance,
		arg.ElapsedTime,
		arg.StartIndex,
		arg.EndIndex,
		arg.LapIndex,
		arg.MaxSpeed,
		arg.MovingTime,
		arg.Name,
		arg.PaceZone,
		arg.Split,
		arg.StartDate,
		arg.StartDateLocal,
		arg.TotalElevationGain,
	)
	return err
}
