// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type StravaUser struct {
	ID                    uuid.UUID      `json:"id"`
	UserID                uuid.UUID      `json:"user_id"`
	StravaID              int64          `json:"strava_id"`
	RefreshToken          string         `json:"refresh_token"`
	RefreshTokenExpiresAt time.Time      `json:"refresh_token_expires_at"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	Username              string         `json:"username"`
	Firstname             sql.NullString `json:"firstname"`
	Lastname              sql.NullString `json:"lastname"`
	City                  sql.NullString `json:"city"`
	State                 sql.NullString `json:"state"`
	Country               sql.NullString `json:"country"`
	Sex                   sql.NullString `json:"sex"`
	Premuim               sql.NullBool   `json:"premuim"`
	Weight                sql.NullInt32  `json:"weight"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
