-- +goose up
CREATE TABLE REFRESH_TOKENS (
    token VARCHAR(256) PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP NULL
);

-- +goose down
DROP TABLE REFRESH_TOKENS;

