name: ci

on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      DB_URL: postgres://user:password@localhost:5432/testdb?sslmode=disable

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb

    steps: 
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U user; do
            echo "Waiting for PostgreSQL...";
            sleep 2;
          done

     - name: 'Install goose'
        run: 'go install github.com/pressly/goose/v3/cmd/goose@latest'

      - name: Create tables
        run: './scripts/migrateup.sh'

      - name: Run unit tests
        run: go test -cover ./...

